#!/usr/bin/env bash
# Circular Planner — air-gapped installer
# Run this from inside the extracted archive on the target machine.
# No internet access is required.
set -euo pipefail

# ─── Safety: refuse root ──────────────────────────────────────────────────────
if [ "$EUID" -eq 0 ]; then
  echo "Do not run as root. Re-run as an unprivileged user." >&2
  exit 1
fi

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}$*${NC}"; }
warn()  { echo -e "${YELLOW}$*${NC}"; }
err()   { echo -e "${RED}$*${NC}" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || { err "ERROR: required command '$1' not found."; exit 1; }
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ─── Verify archive contents ─────────────────────────────────────────────────
if [ ! -d "$SCRIPT_DIR/bare-metal" ]; then
  err "ERROR: bare-metal/ directory not found. Run this script from inside the extracted archive."
  exit 1
fi

echo ""
echo "============================================"
echo "   Circular Planner — Air-Gapped Install"
echo "============================================"
echo ""

if [ -f "$SCRIPT_DIR/BUILD_INFO" ]; then
  head -6 "$SCRIPT_DIR/BUILD_INFO"
  echo ""
fi

require openssl

# ─── Prompt: install mode ─────────────────────────────────────────────────────
HAS_DOCKER=false
if [ -d "$SCRIPT_DIR/images" ] && [ -f "$SCRIPT_DIR/docker-compose.airgap.yml" ]; then
  HAS_DOCKER=true
fi

if [ "$HAS_DOCKER" = true ]; then
  read -r -p "Install with (1) Docker or (2) bare-metal Node+Postgres? [1/2] (default 1): " MODE
  MODE="${MODE:-1}"
else
  warn "Docker images not found in archive. Using bare-metal install."
  MODE="2"
fi

case "$MODE" in
  1) MODE_NAME="Docker" ;;
  2) MODE_NAME="bare-metal" ;;
  *) err "Invalid choice: $MODE"; exit 1 ;;
esac

# ─── Prompt: install directory (bare-metal only) ─────────────────────────────
INSTALL_DIR=""
if [ "$MODE" = "2" ]; then
  DEFAULT_DIR="$(pwd)/circular-planner"
  read -r -p "Install directory [${DEFAULT_DIR}]: " INSTALL_DIR
  INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_DIR}"
fi

# ─── Prompt: admin credentials ────────────────────────────────────────────────
read -r -p "Admin username: " ADMIN_USER
[ -n "$ADMIN_USER" ] || { err "Username required."; exit 1; }
read -r -p "Admin email: " ADMIN_EMAIL
[ -n "$ADMIN_EMAIL" ] || { err "Email required."; exit 1; }
while :; do
  read -r -s -p "Admin password (>=8 chars): " ADMIN_PASS; echo
  if [ "${#ADMIN_PASS}" -lt 8 ]; then
    warn "Password too short -- try again."; continue
  fi
  read -r -s -p "Confirm password: " ADMIN_PASS2; echo
  [ "$ADMIN_PASS" = "$ADMIN_PASS2" ] && break
  warn "Passwords did not match -- try again."
done

# ─── .env overwrite guard ─────────────────────────────────────────────────────
ENV_DIR="$INSTALL_DIR"
[ "$MODE" = "1" ] && ENV_DIR="$(pwd)"

if [ -f "$ENV_DIR/.env" ]; then
  read -r -p ".env already exists at ${ENV_DIR}. Overwrite? [y/N]: " OVER
  case "$OVER" in
    y|Y|yes|YES) ;;
    *) err "Aborting so .env is preserved."; exit 1 ;;
  esac
fi

# ─── Generate secrets ─────────────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
PORT=3000

# ─── Docker path ──────────────────────────────────────────────────────────────
if [ "$MODE" = "1" ]; then
  require docker
  if ! docker compose version >/dev/null 2>&1; then
    err "ERROR: 'docker compose' (v2 plugin) not available. Install Docker first."
    exit 1
  fi

  info "Loading Docker images from archive..."
  docker load -i "$SCRIPT_DIR/images/node-20.18-alpine.tar"
  info "  Loaded node:20.18-alpine"
  docker load -i "$SCRIPT_DIR/images/postgres-16-alpine.tar"
  info "  Loaded postgres:16-alpine"
  docker load -i "$SCRIPT_DIR/images/circular-planner-app.tar"
  info "  Loaded circular-planner:latest"

  POSTGRES_PASSWORD=$(openssl rand -hex 16)

  cat > .env <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
NODE_ENV=production
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
ALLOW_REGISTRATION=false
POSTGRES_USER=planner
POSTGRES_DB=circular_planner
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://planner:${POSTGRES_PASSWORD}@db:5432/circular_planner
EOF
  info "Wrote .env"

  COMPOSE_FILE="$SCRIPT_DIR/docker-compose.airgap.yml"

  info "Starting containers..."
  docker compose -f "$COMPOSE_FILE" up -d

  info "Waiting for app to become healthy..."
  HEALTHY=0
  for _ in $(seq 1 60); do
    # Use bash built-in /dev/tcp — no curl/wget needed on minimal Debian installs.
    if (exec 3<>"/dev/tcp/127.0.0.1/${PORT}") 2>/dev/null; then
      exec 3<&- 2>/dev/null || true
      HEALTHY=1; break
    fi
    sleep 1
  done
  if [ "$HEALTHY" -ne 1 ]; then
    err "App did not become healthy within 60s. Check: docker compose -f \"$COMPOSE_FILE\" logs"
    exit 1
  fi
  info "App is up"

  info "Seeding admin user..."
  docker compose -f "$COMPOSE_FILE" exec -T app \
    node dist/server/scripts/create-admin.js \
    --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS"

# ─── Bare-metal path ──────────────────────────────────────────────────────────
else
  # ── Optional: install bundled .deb packages for nodejs + postgresql-client ──
  HAS_DEBS=false
  if [ -d "$SCRIPT_DIR/debs" ] && ls "$SCRIPT_DIR/debs"/*.deb >/dev/null 2>&1; then
    HAS_DEBS=true
  fi

  NEED_PREREQS=false
  command -v node   >/dev/null 2>&1 || command -v nodejs >/dev/null 2>&1 || NEED_PREREQS=true
  command -v psql   >/dev/null 2>&1 || NEED_PREREQS=true

  if [ "$HAS_DEBS" = true ] && [ "$NEED_PREREQS" = true ]; then
    echo ""
    warn "nodejs and/or postgresql-client not found on this machine."
    info "The archive includes bundled .deb packages that can install them offline."

    # Warn if packaging host codename doesn't match this host's codename.
    TARGET_CODENAME="unknown"
    if [ -f /etc/os-release ]; then
      TARGET_CODENAME=$(. /etc/os-release && echo "${VERSION_CODENAME:-${ID:-unknown}}")
    fi
    BUILD_CODENAME=$(grep '^Codename:' "$SCRIPT_DIR/BUILD_INFO" 2>/dev/null | awk '{print $2}')
    if [ -n "$BUILD_CODENAME" ] && [ "$BUILD_CODENAME" != "unknown" ] && \
       [ "$TARGET_CODENAME" != "$BUILD_CODENAME" ]; then
      warn "WARNING: These .debs were built for '${BUILD_CODENAME}' but this host is '${TARGET_CODENAME}'."
      warn "         Installing may fail or cause conflicts. Proceed with caution."
    fi

    read -r -p "Install bundled .deb packages now (requires sudo)? [Y/n]: " INST_DEBS
    INST_DEBS="${INST_DEBS:-Y}"
    case "$INST_DEBS" in
      y|Y|yes|YES)
        info "Running: sudo dpkg -i ${SCRIPT_DIR}/debs/*.deb"
        if ! sudo dpkg -i "$SCRIPT_DIR"/debs/*.deb; then
          warn "dpkg reported errors (possibly missing dependencies)."
          warn "Attempting to fix: sudo apt-get install -f --no-download"
          sudo apt-get install -f --no-download -y 2>/dev/null || \
            warn "apt-get -f also failed — you may need to resolve dependencies manually."
        fi
        ;;
      *) warn "Skipping .deb install. Make sure nodejs 18+ and postgresql-client are installed before continuing." ;;
    esac
  fi

  # Debian/Ubuntu ships Node.js as "nodejs"; other distros use "node".
  if command -v node >/dev/null 2>&1; then
    NODE=node
  elif command -v nodejs >/dev/null 2>&1; then
    NODE=nodejs
  else
    err "ERROR: Node.js not found."
    if [ "$HAS_DEBS" = false ]; then
      err "  This archive has no bundled .debs. Install Node.js 18+ manually, then re-run."
    else
      err "  The .deb install may have failed. Check errors above, then re-run."
    fi
    exit 1
  fi
  require psql
  NODE_MAJOR=$($NODE -v | sed 's/v//' | cut -d. -f1)
  if [ "$NODE_MAJOR" -lt 18 ]; then
    err "Node.js 18+ required (found $($NODE -v))."; exit 1
  fi
  info "Node $($NODE -v), psql present"

  # DB connection prompt
  echo ""
  echo "Database connection:"
  echo "  (a) Local Postgres (default DSN uses your \$USER)"
  echo "  (b) Remote Postgres (provide full DATABASE_URL)"
  read -r -p "Choice [a/b] (default a): " DBCHOICE
  DBCHOICE="${DBCHOICE:-a}"
  if [ "$DBCHOICE" = "a" ] || [ "$DBCHOICE" = "A" ]; then
    DEFAULT_DSN="postgresql://${USER}@localhost:5432/circular_planner"
    read -r -p "DATABASE_URL [${DEFAULT_DSN}]: " DB_URL
    DB_URL="${DB_URL:-$DEFAULT_DSN}"
  else
    read -r -p "DATABASE_URL: " DB_URL
    [ -n "$DB_URL" ] || { err "DATABASE_URL required."; exit 1; }
  fi

  # Connection test
  attempt=0
  while :; do
    attempt=$((attempt+1))
    if ERR=$(psql "$DB_URL" -c 'SELECT 1' 2>&1 >/dev/null); then
      info "Database connection OK"
      break
    fi
    err "Connection failed: $ERR"
    if [ "$attempt" -ge 2 ]; then
      err "Giving up. Fix DATABASE_URL or DB and re-run."
      exit 1
    fi
    echo ""
    warn "If the database does not exist, ask your DBA to run:"
    cat <<'SQL'

  CREATE DATABASE circular_planner;
  CREATE USER planner WITH PASSWORD 'choose-a-strong-password';
  GRANT ALL PRIVILEGES ON DATABASE circular_planner TO planner;

SQL
    read -r -p "Press Enter to retry once the database exists (or Ctrl-C to abort)... " _
  done

  # Create install directory and copy artifacts
  info "Installing to ${INSTALL_DIR}..."
  mkdir -p "$INSTALL_DIR"
  cp -r "$SCRIPT_DIR/bare-metal/node_modules" "$INSTALL_DIR/"
  cp -r "$SCRIPT_DIR/bare-metal/dist"         "$INSTALL_DIR/"
  cp -r "$SCRIPT_DIR/bare-metal/public"       "$INSTALL_DIR/"
  cp    "$SCRIPT_DIR/bare-metal/package.json"  "$INSTALL_DIR/"

  cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
NODE_ENV=production
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
ALLOW_REGISTRATION=false
DATABASE_URL=${DB_URL}
EOF
  info "Wrote .env"

  info "Running migrations and seeding admin..."
  (cd "$INSTALL_DIR" && $NODE dist/server/scripts/create-admin.js \
    --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS")

  # ── systemd service ──────────────────────────────────────────────────────────
  NODE_PATH=$(command -v "$NODE")
  SERVICE_FILE="$INSTALL_DIR/circular-planner.service"
  SERVICE_USER="${SUDO_USER:-$USER}"

  cat > "$SERVICE_FILE" <<UNIT
[Unit]
Description=Circular Planner
After=network.target postgresql.service

[Service]
Type=simple
User=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=${NODE_PATH} ${INSTALL_DIR}/dist/server/index.js
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

  SYSTEMD_OK=false
  if command -v systemctl >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
    read -r -p "Install and enable systemd service (requires sudo)? [Y/n]: " INST_SVC
    INST_SVC="${INST_SVC:-Y}"
    case "$INST_SVC" in
      y|Y|yes|YES)
        sudo install -m 0644 "$SERVICE_FILE" /etc/systemd/system/circular-planner.service
        sudo systemctl daemon-reload
        sudo systemctl enable --now circular-planner.service
        SYSTEMD_OK=true
        info "Service installed and started."
        ;;
    esac
  fi

  if [ "$SYSTEMD_OK" = false ]; then
    warn "Systemd service not installed automatically."
    warn "To install it manually:"
    warn "  sudo cp ${SERVICE_FILE} /etc/systemd/system/"
    warn "  sudo systemctl daemon-reload"
    warn "  sudo systemctl enable --now circular-planner"
  fi
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}   Installation complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo "  Mode:      ${MODE_NAME}"
echo "  URL:       http://localhost:${PORT}"
echo "  Admin:     ${ADMIN_USER} <${ADMIN_EMAIL}>"
echo ""
warn "Registration is CLOSED (ALLOW_REGISTRATION=false)."
warn "To reopen: set ALLOW_REGISTRATION=true in .env and restart."
echo ""
warn "HTTPS is NOT configured. For production, either:"
warn "  set TLS_CERT_FILE and TLS_KEY_FILE in .env, or"
warn "  put a reverse proxy in front and set TRUST_PROXY=true."
echo ""
if [ "$MODE" = "2" ]; then
  if [ "${SYSTEMD_OK:-false}" = true ]; then
    echo "Service management:"
    echo "  sudo systemctl status  circular-planner"
    echo "  sudo systemctl restart circular-planner"
    echo "  sudo systemctl stop    circular-planner"
  else
    echo "Start the server:"
    echo "  cd ${INSTALL_DIR}"
    echo "  ${NODE} dist/server/index.js"
    echo ""
    echo "Or install the generated service file:"
    echo "  sudo cp ${INSTALL_DIR}/circular-planner.service /etc/systemd/system/"
    echo "  sudo systemctl daemon-reload && sudo systemctl enable --now circular-planner"
  fi
  echo ""
fi
