#!/usr/bin/env bash
# Circular Planner — air-gapped installer (Go backend)
# Run this from inside the extracted archive on the target machine.
# No internet access is required.
set -euo pipefail

if [ "$EUID" -eq 0 ]; then
  echo "Do not run as root. Re-run as an unprivileged user." >&2
  exit 1
fi

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}$*${NC}"; }
warn() { echo -e "${YELLOW}$*${NC}"; }
err()  { echo -e "${RED}$*${NC}" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || { err "ERROR: required command '$1' not found."; exit 1; }
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f "$SCRIPT_DIR/bare-metal/planner" ]; then
  err "ERROR: bare-metal/planner not found. Run this script from inside the extracted archive."
  exit 1
fi

echo ""
echo "============================================"
echo "   Circular Planner — Air-Gapped Install"
echo "   (Go backend)"
echo "============================================"
echo ""

if [ -f "$SCRIPT_DIR/BUILD_INFO" ]; then
  head -8 "$SCRIPT_DIR/BUILD_INFO"
  echo ""
fi

require openssl

# ─── Detect available paths ──────────────────────────────────────────────────
HAS_DOCKER=false
HAS_POSTGRES_IMAGE=false
if [ -f "$SCRIPT_DIR/images/circular-planner-app.tar" ] && [ -f "$SCRIPT_DIR/docker-compose.airgap.yml" ]; then
  HAS_DOCKER=true
fi
[ -f "$SCRIPT_DIR/images/postgres-16-alpine.tar" ] && HAS_POSTGRES_IMAGE=true

# ─── Prompt: install mode ────────────────────────────────────────────────────
if [ "$HAS_DOCKER" = true ]; then
  read -r -p "Install with (1) Docker or (2) bare-metal binary? [1/2] (default 1): " MODE
  MODE="${MODE:-1}"
else
  warn "Docker images not found in archive. Using bare-metal install."
  MODE="2"
fi

case "$MODE" in
  1) MODE_NAME="Docker" ;;
  2) MODE_NAME="bare-metal" ;;
  *) err "Invalid choice: $MODE"; exit 1 ;;
esac

INSTALL_DIR=""
if [ "$MODE" = "2" ]; then
  DEFAULT_DIR="$(pwd)/circular-planner"
  read -r -p "Install directory [${DEFAULT_DIR}]: " INSTALL_DIR
  INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_DIR}"
fi

# ─── Admin credentials ────────────────────────────────────────────────────────
read -r -p "Admin username: " ADMIN_USER
[ -n "$ADMIN_USER" ] || { err "Username required."; exit 1; }
read -r -p "Admin email: " ADMIN_EMAIL
[ -n "$ADMIN_EMAIL" ] || { err "Email required."; exit 1; }
while :; do
  read -r -s -p "Admin password (>=8 chars): " ADMIN_PASS; echo
  if [ "${#ADMIN_PASS}" -lt 8 ]; then
    warn "Password too short -- try again."; continue
  fi
  read -r -s -p "Confirm password: " ADMIN_PASS2; echo
  [ "$ADMIN_PASS" = "$ADMIN_PASS2" ] && break
  warn "Passwords did not match -- try again."
done

# ─── .env overwrite guard ────────────────────────────────────────────────────
ENV_DIR="$INSTALL_DIR"
[ "$MODE" = "1" ] && ENV_DIR="$(pwd)"

if [ -f "$ENV_DIR/.env" ]; then
  read -r -p ".env already exists at ${ENV_DIR}. Overwrite? [y/N]: " OVER
  case "$OVER" in
    y|Y|yes|YES) ;;
    *) err "Aborting so .env is preserved."; exit 1 ;;
  esac
fi

JWT_SECRET=$(openssl rand -hex 32)
PORT=3000

# ─── Docker path ──────────────────────────────────────────────────────────────
if [ "$MODE" = "1" ]; then
  require docker
  if ! docker compose version >/dev/null 2>&1; then
    err "ERROR: 'docker compose' (v2 plugin) not available. Install Docker first."
    exit 1
  fi

  info "Loading Docker image from archive..."
  docker load -i "$SCRIPT_DIR/images/circular-planner-app.tar"
  info "  Loaded circular-planner:latest"

  if [ "$HAS_POSTGRES_IMAGE" = true ]; then
    docker load -i "$SCRIPT_DIR/images/postgres-16-alpine.tar"
    info "  Loaded postgres:16-alpine"
    POSTGRES_PASSWORD=$(openssl rand -hex 16)
    cat > .env <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
EOF
  else
    cat > .env <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
# SQLite backend — no DATABASE_URL needed (defaults to sqlite:./data/planner.db)
EOF
  fi
  info "Wrote .env"

  cp "$SCRIPT_DIR/docker-compose.airgap.yml" ./docker-compose.airgap.yml

  info "Starting containers..."
  docker compose -f docker-compose.airgap.yml up -d

  info "Waiting for app to become healthy..."
  HEALTHY=0
  for _ in $(seq 1 60); do
    if curl -fsS "http://localhost:${PORT}/index.html" >/dev/null 2>&1; then
      HEALTHY=1; break
    fi
    sleep 1
  done
  if [ "$HEALTHY" -ne 1 ]; then
    err "App did not become healthy within 60s. Check: docker compose -f docker-compose.airgap.yml logs"
    exit 1
  fi
  info "App is up"

  info "Seeding admin user..."
  docker compose -f docker-compose.airgap.yml exec -T app \
    ./planner --create-admin --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS"

# ─── Bare-metal path ──────────────────────────────────────────────────────────
else
  info "Installing to ${INSTALL_DIR}..."
  mkdir -p "$INSTALL_DIR/data"
  cp "$SCRIPT_DIR/bare-metal/planner" "$INSTALL_DIR/"
  chmod +x "$INSTALL_DIR/planner"

  cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
DATABASE_URL=sqlite:./data/planner.db
EOF
  info "Wrote .env"

  info "Running migrations and seeding admin..."
  (cd "$INSTALL_DIR" && ./planner --create-admin \
    --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS")
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}   Installation complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo "  Mode:      ${MODE_NAME}"
echo "  URL:       http://localhost:${PORT}"
echo "  Admin:     ${ADMIN_USER} <${ADMIN_EMAIL}>"
echo ""
warn "HTTPS is NOT configured. For production, either:"
warn "  set TLS_CERT_FILE and TLS_KEY_FILE in .env, or"
warn "  put a reverse proxy in front and set TRUST_PROXY=true."
echo ""
if [ "$MODE" = "2" ]; then
  echo "Start the server:"
  echo "  cd ${INSTALL_DIR}"
  echo "  ./planner"
  echo ""
fi
