#!/usr/bin/env bash
# Circular Planner — interactive installer
# Supports Docker or bare-metal Node+Postgres. Never runs as root, never uses sudo.
set -euo pipefail

# ─── Safety: refuse root ──────────────────────────────────────────────────────
if [ "$EUID" -eq 0 ]; then
  echo "Do not run as root. Re-run as an unprivileged user." >&2
  exit 1
fi

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}$*${NC}"; }
warn()  { echo -e "${YELLOW}$*${NC}"; }
err()   { echo -e "${RED}$*${NC}" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || { err "ERROR: required command '$1' not found."; exit 1; }
}

echo ""
echo "============================================"
echo "   Circular Planner — Installation Script"
echo "============================================"
echo ""

require openssl

# ─── Prompt: install mode ─────────────────────────────────────────────────────
read -r -p "Install with (1) Docker or (2) bare-metal Node+Postgres? [1/2] (default 1): " MODE
MODE="${MODE:-1}"
case "$MODE" in
  1) MODE_NAME="Docker" ;;
  2) MODE_NAME="bare-metal" ;;
  *) err "Invalid choice: $MODE"; exit 1 ;;
esac

# ─── Prompt: admin credentials ────────────────────────────────────────────────
read -r -p "Admin username: " ADMIN_USER
[ -n "$ADMIN_USER" ] || { err "Username required."; exit 1; }
read -r -p "Admin email: " ADMIN_EMAIL
[ -n "$ADMIN_EMAIL" ] || { err "Email required."; exit 1; }
while :; do
  read -r -s -p "Admin password (≥8 chars): " ADMIN_PASS; echo
  if [ "${#ADMIN_PASS}" -lt 8 ]; then
    warn "Password too short — try again."; continue
  fi
  read -r -s -p "Confirm password: " ADMIN_PASS2; echo
  [ "$ADMIN_PASS" = "$ADMIN_PASS2" ] && break
  warn "Passwords did not match — try again."
done

# ─── Prompt: branding ─────────────────────────────────────────────────────────
read -r -p "App name shown in the header [Circular Planner]: " APP_NAME
APP_NAME="${APP_NAME:-Circular Planner}"
read -r -p "Logo URL (leave blank for default SVG): " APP_LOGO_URL

# ─── .env overwrite guard ─────────────────────────────────────────────────────
if [ -f .env ]; then
  read -r -p ".env already exists. Overwrite? [y/N]: " OVER
  case "$OVER" in
    y|Y|yes|YES) ;;
    *) err "Aborting so .env is preserved."; exit 1 ;;
  esac
fi

# ─── Generate secrets ─────────────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)
PORT=3000

# ─── Docker path ──────────────────────────────────────────────────────────────
if [ "$MODE" = "1" ]; then
  require docker
  if ! docker compose version >/dev/null 2>&1; then
    err "ERROR: 'docker compose' (v2 plugin) not available. Install Docker Desktop or the compose plugin."
    exit 1
  fi

  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  cat > .env <<EOF
# Generated by install.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
NODE_ENV=production
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
ALLOW_REGISTRATION=false
POSTGRES_USER=planner
POSTGRES_DB=circular_planner
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://planner:${POSTGRES_PASSWORD}@postgres:5432/circular_planner
APP_NAME=${APP_NAME}
APP_LOGO_URL=${APP_LOGO_URL}
EOF
  info "✓ Wrote .env"

  info "Building and starting containers…"
  docker compose up -d --build

  info "Waiting for app to become healthy…"
  HEALTHY=0
  for _ in $(seq 1 60); do
    if curl -fsS "http://localhost:${PORT}/index.html" >/dev/null 2>&1; then
      HEALTHY=1; break
    fi
    sleep 1
  done
  if [ "$HEALTHY" -ne 1 ]; then
    err "App did not become healthy within 60s. Check: docker compose logs"
    exit 1
  fi
  info "✓ App is up"

  info "Seeding admin user…"
  if ! docker compose exec -T app npm run create-admin -- \
    --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS"; then
    err "Failed to create admin user. Recent logs:"
    docker compose logs --tail=50 app >&2
    exit 1
  fi

# ─── Bare-metal path ──────────────────────────────────────────────────────────
else
  require node
  require npm
  require psql
  NODE_MAJOR=$(node -v | sed 's/v//' | cut -d. -f1)
  if [ "$NODE_MAJOR" -lt 18 ]; then
    err "Node.js 18+ required (found $(node -v))."; exit 1
  fi
  info "✓ Node $(node -v), npm $(npm -v), psql present"

  # DB connection prompt
  echo ""
  echo "Database connection:"
  echo "  (a) Local Postgres (default DSN uses your \$USER)"
  echo "  (b) Remote Postgres (provide full DATABASE_URL)"
  read -r -p "Choice [a/b] (default a): " DBCHOICE
  DBCHOICE="${DBCHOICE:-a}"
  if [ "$DBCHOICE" = "a" ] || [ "$DBCHOICE" = "A" ]; then
    DEFAULT_DSN="postgresql://${USER}@localhost:5432/circular_planner"
    read -r -p "DATABASE_URL [${DEFAULT_DSN}]: " DB_URL
    DB_URL="${DB_URL:-$DEFAULT_DSN}"
  else
    read -r -p "DATABASE_URL: " DB_URL
    [ -n "$DB_URL" ] || { err "DATABASE_URL required."; exit 1; }
  fi

  # Connection test — loop once to allow DBA-created DB
  attempt=0
  while :; do
    attempt=$((attempt+1))
    if ERR=$(psql "$DB_URL" -c 'SELECT 1' 2>&1 >/dev/null); then
      info "✓ Database connection OK"
      break
    fi
    err "Connection failed: $ERR"
    if [ "$attempt" -ge 2 ]; then
      err "Giving up. Fix DATABASE_URL or DB and re-run."
      exit 1
    fi
    echo ""
    warn "If the database does not exist, ask your DBA to run:"
    cat <<'SQL'

  CREATE DATABASE circular_planner;
  CREATE USER planner WITH PASSWORD 'choose-a-strong-password';
  GRANT ALL PRIVILEGES ON DATABASE circular_planner TO planner;

SQL
    read -r -p "Press Enter to retry once the database exists (or Ctrl-C to abort)… " _
  done

  cat > .env <<EOF
# Generated by install.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
NODE_ENV=production
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
ALLOW_REGISTRATION=false
DATABASE_URL=${DB_URL}
APP_NAME=${APP_NAME}
APP_LOGO_URL=${APP_LOGO_URL}
EOF
  info "✓ Wrote .env"

  info "Installing dependencies…"
  npm ci
  info "Building…"
  npm run build

  info "Running migrations and seeding admin…"
  npm run create-admin -- \
    --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS"
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}   Installation complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo "  Mode:      ${MODE_NAME}"
echo "  URL:       http://localhost:${PORT}"
echo "  Admin:     ${ADMIN_USER} <${ADMIN_EMAIL}>"
echo ""
warn "Registration is CLOSED (ALLOW_REGISTRATION=false)."
warn "To reopen: set ALLOW_REGISTRATION=true in .env and restart."
echo ""
warn "HTTPS is NOT configured. For production, either:"
warn "  • set TLS_CERT_FILE and TLS_KEY_FILE in .env, or"
warn "  • put a reverse proxy in front and set TRUST_PROXY=true."
echo ""
if [ "$MODE" = "2" ]; then
  echo "Start the server:  npm start"
  echo ""
fi
