#!/usr/bin/env bash
# Circular Planner — air-gapped installer (Go backend)
# Run this from inside the extracted archive on the target machine.
# No internet access is required.
set -euo pipefail

if [ "$EUID" -eq 0 ]; then
  echo "Do not run as root. Re-run as an unprivileged user." >&2
  exit 1
fi

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}$*${NC}"; }
warn() { echo -e "${YELLOW}$*${NC}"; }
err()  { echo -e "${RED}$*${NC}" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || { err "ERROR: required command '$1' not found."; exit 1; }
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f "$SCRIPT_DIR/bare-metal/planner" ]; then
  err "ERROR: bare-metal/planner not found. Run this script from inside the extracted archive."
  exit 1
fi

echo ""
echo "============================================"
echo "   Circular Planner — Air-Gapped Install"
echo "   (Go backend)"
echo "============================================"
echo ""

if [ -f "$SCRIPT_DIR/BUILD_INFO" ]; then
  head -8 "$SCRIPT_DIR/BUILD_INFO"
  echo ""
fi

require openssl

# ─── Detect available paths ──────────────────────────────────────────────────
HAS_DOCKER=false
HAS_POSTGRES_IMAGE=false
if [ -f "$SCRIPT_DIR/images/circular-planner-app.tar" ] && [ -f "$SCRIPT_DIR/docker-compose.airgap.yml" ]; then
  HAS_DOCKER=true
fi
[ -f "$SCRIPT_DIR/images/postgres-16-alpine.tar" ] && HAS_POSTGRES_IMAGE=true

# ─── Prompt: install mode ────────────────────────────────────────────────────
if [ "$HAS_DOCKER" = true ]; then
  read -r -p "Install with (1) Docker or (2) bare-metal binary? [1/2] (default 1): " MODE
  MODE="${MODE:-1}"
else
  warn "Docker images not found in archive. Using bare-metal install."
  MODE="2"
fi

case "$MODE" in
  1) MODE_NAME="Docker" ;;
  2) MODE_NAME="bare-metal" ;;
  *) err "Invalid choice: $MODE"; exit 1 ;;
esac

INSTALL_DIR=""
if [ "$MODE" = "2" ]; then
  DEFAULT_DIR="$(pwd)/circular-planner"
  read -r -p "Install directory [${DEFAULT_DIR}]: " INSTALL_DIR
  INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_DIR}"
fi

# ─── Detect existing installation ────────────────────────────────────────────
ENV_DIR="$INSTALL_DIR"
[ "$MODE" = "1" ] && ENV_DIR="$(pwd)"

UPGRADE=false
if [ -f "$ENV_DIR/.env" ]; then
  echo ""
  warn "Existing .env detected at: ${ENV_DIR}/.env"
  echo "  This usually means an instance is already installed here with its own database."
  echo ""
  echo "  (u) Upgrade  — keep .env and database, replace binary/scripts; migrations run on restart"
  echo "  (f) Fresh    — overwrite .env and reseed admin (regenerates JWT_SECRET; logs out users)"
  echo "  (a) Abort"
  echo ""
  read -r -p "Choice [u/f/a] (default u): " CHOICE
  CHOICE="${CHOICE:-u}"
  case "$CHOICE" in
    u|U|upgrade) UPGRADE=true ;;
    f|F|fresh)   UPGRADE=false ;;
    *)           err "Aborting."; exit 1 ;;
  esac
fi

# ─── Admin credentials (fresh install only) ──────────────────────────────────
if [ "$UPGRADE" = false ]; then
  read -r -p "Admin username: " ADMIN_USER
  [ -n "$ADMIN_USER" ] || { err "Username required."; exit 1; }
  read -r -p "Admin email: " ADMIN_EMAIL
  [ -n "$ADMIN_EMAIL" ] || { err "Email required."; exit 1; }
  while :; do
    read -r -s -p "Admin password (>=8 chars): " ADMIN_PASS; echo
    if [ "${#ADMIN_PASS}" -lt 8 ]; then
      warn "Password too short -- try again."; continue
    fi
    read -r -s -p "Confirm password: " ADMIN_PASS2; echo
    [ "$ADMIN_PASS" = "$ADMIN_PASS2" ] && break
    warn "Passwords did not match -- try again."
  done
  JWT_SECRET=$(openssl rand -hex 32)
fi

# Pick PORT from existing .env on upgrade so the health check hits the right port
if [ "$UPGRADE" = true ]; then
  PORT=$(grep -E '^PORT=' "$ENV_DIR/.env" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'")
  PORT="${PORT:-3000}"
else
  PORT=3000
fi

# ─── Docker path ──────────────────────────────────────────────────────────────
if [ "$MODE" = "1" ]; then
  require docker
  if ! docker compose version >/dev/null 2>&1; then
    err "ERROR: 'docker compose' (v2 plugin) not available. Install Docker first."
    exit 1
  fi

  info "Loading Docker image from archive..."
  docker load -i "$SCRIPT_DIR/images/circular-planner-app.tar"
  info "  Loaded circular-planner:latest"

  if [ "$HAS_POSTGRES_IMAGE" = true ]; then
    docker load -i "$SCRIPT_DIR/images/postgres-16-alpine.tar"
    info "  Loaded postgres:16-alpine"
  fi

  if [ "$UPGRADE" = false ]; then
    if [ "$HAS_POSTGRES_IMAGE" = true ]; then
      POSTGRES_PASSWORD=$(openssl rand -hex 16)
      cat > .env <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
EOF
    else
      cat > .env <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
# SQLite backend — no DATABASE_URL needed (defaults to sqlite:./data/planner.db)
EOF
    fi
    info "Wrote .env"
  else
    info "Keeping existing .env"
  fi

  cp "$SCRIPT_DIR/docker-compose.airgap.yml" ./docker-compose.airgap.yml

  if [ "$UPGRADE" = true ]; then
    info "Recreating containers with new image (data volumes preserved)..."
    docker compose -f docker-compose.airgap.yml up -d --force-recreate
  else
    info "Starting containers..."
    docker compose -f docker-compose.airgap.yml up -d
  fi

  info "Waiting for app to become healthy..."
  HEALTHY=0
  for _ in $(seq 1 60); do
    if curl -fsS "http://localhost:${PORT}/index.html" >/dev/null 2>&1; then
      HEALTHY=1; break
    fi
    sleep 1
  done
  if [ "$HEALTHY" -ne 1 ]; then
    err "App did not become healthy within 60s. Check: docker compose -f docker-compose.airgap.yml logs"
    exit 1
  fi
  info "App is up"

  if [ "$UPGRADE" = false ]; then
    info "Seeding admin user..."
    docker compose -f docker-compose.airgap.yml exec -T app \
      ./planner --create-admin --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS"
  fi

# ensure_env_var KEY VALUE FILE
#
# Adds KEY=VALUE to FILE if the key is absent; leaves an existing value alone so
# repeat upgrades never duplicate a line or clobber an operator's edit.
#
# This exists because .env is written ONLY on fresh install (see the heredoc in
# the else-branch below). The upgrade branch copies the binary and scripts and
# nothing else, so without this any setting introduced by a new release would
# never reach an already-installed machine — which is the only machine that
# matters here.
ensure_env_var() {
  _k="$1"; _v="$2"; _f="$3"
  [ -f "$_f" ] || return 0
  if grep -qE "^[[:space:]]*${_k}=" "$_f"; then
    return 0
  fi
  printf '%s=%s\n' "$_k" "$_v" >> "$_f"
  info "Added ${_k} to .env"
}

# ─── Bare-metal path ──────────────────────────────────────────────────────────
else
  if [ "$UPGRADE" = true ]; then
    info "Upgrading installation in ${INSTALL_DIR}..."

    # Keep the outgoing binary so a bad build can be undone on the spot.
    # This machine is air-gapped: without a local copy, recovering from a
    # broken release means building a new tarball on a connected machine and
    # physically carrying it back, which can take days. Renaming is safe while
    # the service is running — the kernel keeps the open inode alive until the
    # process restarts.
    if [ -f "$INSTALL_DIR/planner" ]; then
      mv -f "$INSTALL_DIR/planner" "$INSTALL_DIR/planner.prev"
      info "Kept previous binary as planner.prev"
    fi

    cp "$SCRIPT_DIR/bare-metal/planner" "$INSTALL_DIR/"
    chmod +x "$INSTALL_DIR/planner"
    info "Replaced planner binary"

    if [ -d "$SCRIPT_DIR/bare-metal/scripts" ]; then
      cp -r "$SCRIPT_DIR/bare-metal/scripts" "$INSTALL_DIR/"
      chmod +x "$INSTALL_DIR/scripts/"*.sh 2>/dev/null || true
      info "Updated scripts/"
    fi

    # Bring new settings to an already-installed box. Without these two the
    # release's safety features exist in the binary but are never switched on.
    ensure_env_var "MIGRATE_ON_STARTUP" "false" "$INSTALL_DIR/.env"
    ensure_env_var "BACKUP_DIR" "./data/backups" "$INSTALL_DIR/.env"

    info "Migrations do NOT run automatically. Apply them explicitly after restart:"
    info "  cd ${INSTALL_DIR} && ./planner migrate dry-run   # review"
    info "  cd ${INSTALL_DIR} && ./planner migrate apply     # backs up, then applies"
  else
    info "Installing to ${INSTALL_DIR}..."
    mkdir -p "$INSTALL_DIR/data"
    cp "$SCRIPT_DIR/bare-metal/planner" "$INSTALL_DIR/"
    chmod +x "$INSTALL_DIR/planner"

    # Install ops scripts alongside the binary
    if [ -d "$SCRIPT_DIR/bare-metal/scripts" ]; then
      cp -r "$SCRIPT_DIR/bare-metal/scripts" "$INSTALL_DIR/"
      chmod +x "$INSTALL_DIR/scripts/"*.sh 2>/dev/null || true
      info "Installed scripts/ (backup.sh, restore.sh, doctor.sh)"
    fi

    cat > "$INSTALL_DIR/.env" <<EOF
# Generated by install-airgap.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
PORT=${PORT}
JWT_SECRET=${JWT_SECRET}
DATABASE_URL=sqlite:./data/planner.db
BACKUP_DIR=./data/backups
MIGRATE_ON_STARTUP=false
EOF
    info "Wrote .env"

    # Apply explicitly: .env sets MIGRATE_ON_STARTUP=false, so the server would
    # otherwise refuse to start with migrations pending and --create-admin would
    # never run.
    info "Applying migrations..."
    (cd "$INSTALL_DIR" && ./planner migrate apply)

    info "Seeding admin..."
    (cd "$INSTALL_DIR" && ./planner --create-admin \
      --username "$ADMIN_USER" --email "$ADMIN_EMAIL" --password "$ADMIN_PASS")
  fi
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================${NC}"
if [ "$UPGRADE" = true ]; then
  echo -e "${GREEN}   Upgrade complete!${NC}"
else
  echo -e "${GREEN}   Installation complete!${NC}"
fi
echo -e "${GREEN}============================================${NC}"
echo "  Mode:      ${MODE_NAME}"
echo "  URL:       http://localhost:${PORT}"
if [ "$UPGRADE" = false ]; then
  echo "  Admin:     ${ADMIN_USER} <${ADMIN_EMAIL}>"
fi
echo ""
if [ "$UPGRADE" = false ]; then
  warn "HTTPS is NOT configured. For production, either:"
  warn "  set TLS_CERT_FILE and TLS_KEY_FILE in .env, or"
  warn "  put a reverse proxy in front and set TRUST_PROXY=true."
  echo ""
fi
if [ "$MODE" = "2" ]; then
  if [ "$UPGRADE" = true ]; then
    if [ -f "$INSTALL_DIR/scripts/doctor.sh" ]; then
      echo "Running preflight check..."
      echo ""
      (cd "$INSTALL_DIR" && bash scripts/doctor.sh) || true
      echo ""
    fi
    echo "Next steps — restart to load the new binary and apply migrations:"
    echo ""
    echo "  If running under systemd:"
    echo "    sudo systemctl restart circular-planner"
    echo "    sudo journalctl -u circular-planner -f   # watch logs"
    echo ""
    echo "  If running manually, stop the existing process and start it again:"
    echo "    cd ${INSTALL_DIR} && ./planner"
    echo ""
    if [ -f "$INSTALL_DIR/planner.prev" ]; then
      echo "  If this release misbehaves, roll back to the previous binary:"
      echo "    cd ${INSTALL_DIR} && mv -f planner.prev planner"
      echo "    sudo systemctl restart circular-planner"
      echo ""
      warn "Rollback restores the BINARY only. Any migrations applied by this"
      warn "release stay applied — they are forward-only. Take a backup before"
      warn "restarting if that matters: cd ${INSTALL_DIR} && ./scripts/backup.sh"
      echo ""
    fi
  else
    # Generate a systemd service file with the actual install path baked in
    WHO=$(whoami)
    cat > "$INSTALL_DIR/circular-planner.service" <<EOF
[Unit]
Description=Circular Planner (Go backend)
After=network.target

[Service]
Type=simple
User=${WHO}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=${INSTALL_DIR}/planner
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
    info "Generated circular-planner.service (paths pre-filled for this install)"
    echo ""

    # Non-fatal preflight check — shows WARN/FAIL for operator review but does not abort install
    if [ -f "$INSTALL_DIR/scripts/doctor.sh" ]; then
      echo "Running preflight check..."
      echo ""
      (cd "$INSTALL_DIR" && bash scripts/doctor.sh) || true
      echo ""
    fi

    echo "Next steps — choose one:"
    echo ""
    echo "  Option A — systemd service (recommended for production):"
    echo "    sudo cp ${INSTALL_DIR}/circular-planner.service /etc/systemd/system/"
    echo "    sudo systemctl daemon-reload"
    echo "    sudo systemctl enable --now circular-planner"
    echo "    sudo journalctl -u circular-planner -f   # watch logs"
    echo ""
    echo "  Option B — run manually (foreground, for testing):"
    echo "    cd ${INSTALL_DIR} && ./planner"
    echo ""
  fi
fi
