ALTER TABLE users ADD COLUMN IF NOT EXISTS gitlab_id       INTEGER UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gitlab_username TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider   TEXT NOT NULL DEFAULT 'local';
